### ISSUE TITLE
Vscode lucks Python 3.10 higlights 

### ISSUE THREAD

**Issue by Arison7** [daltonmenezes/aura-theme#158] opened 2022-07-06 12:32 UTC
First, I would like to say that Aura is the best vscode theme out there.
I am not 100% sure if that's an issue of a theme, but with different themes, it works just fine. 
To put it simple new functions from Python 3.10 are not being highlighted.
![image](https://user-images.githubusercontent.com/89223744/177549409-b71cf946-731c-4dcb-9954-0901110e53dd.png)

best regards,
Arison

**Comment by daltonmenezes** [comment] 2022-07-09 16:06
Hi @Arison7 , thanks.

Could you please give me more details about this? I'm not a Python 3 programmer, so what functions are you talking about from that image? The **match**? I tried that snippet of code, and the other themes only highlight the "eventSource" part. Also, could you provide a screenshot using the theme that makes the highlight properly you are talking about?

The problem is: all the white text has the same scope, unfortunately I can do nothing about this, because if I change the **source.python**, it will change the color for all of **source.python** without distinction.
![Captura de Tela 2022-07-09 às 13 01 42](https://user-images.githubusercontent.com/1149845/178113484-da5fc975-acb9-4c61-a385-028f56ec12d4.png)

**Comment by Arison7** [comment] 2022-07-09 18:59
So "match" is basically "switch" functionality for python added in 3.10. It supposed to be highlighted like this
![image](https://user-images.githubusercontent.com/89223744/178119026-c1f4b24c-8087-4076-bf67-5b2c9b9c9e6f.png)
with "case" and "match" being treated as functions (aura for reference)
![image](https://user-images.githubusercontent.com/89223744/178119053-bd9f6f0e-0385-437b-b48a-36039841f10c.png)
And i think it was done through token type although to be fair I am not sure how the themes exactly works 
![image](https://user-images.githubusercontent.com/89223744/178119293-26bb09b5-881c-48e3-be5a-36e4d0b10029.png)

**Comment by daltonmenezes** [comment] 2022-07-09 19:07
@Arison7 by default vscode doesn't have that **keyword.control** token in this context, probably you are using some extension that adds the python 3 support for these tokens... Could you please share the extensions you are using?

**Comment by daltonmenezes** [comment] 2022-07-11 22:17
@Arison7 what version of vscode are you using? the regular one or inside version?

**Comment by Arison7** [comment] 2022-07-17 11:39
@daltonmenezes I actually needed to do some research about this topic. I didn't know such a thing as an insider version existed. I am using standard vs code.

**Comment by LeandroNardi96** [comment] 2022-08-07 03:38
Hi everyone! Something similar happened to me and I solved it with this parameter in settings.js
![issue_aura_theme](https://user-images.githubusercontent.com/87279657/183273853-f7852b9f-fb0d-4b5e-8db2-6062d94c8b81.png)

Then, my .py files accepted my modified colors because the inspect recognize the semantic token type
![issue_aura_theme_2](https://user-images.githubusercontent.com/87279657/183273993-b9598ee9-23ac-488d-adaf-a851a5945bb3.png)

I hope this solve your problem @Arison7 ! And @daltonmenezes I want to than you for this theme, it's amazing and I love it 🤗

**Comment by daltonmenezes** [comment] 2022-08-09 22:18
Thanks @LeandroNardi96 💜

For all folks who will read it, as the semantic highlighting option must be a personal choice to activate it, I'm closing this issue.

**Closed by daltonmenezes** 2022-08-09 22:18 UTC
